services:
  traefik:
    image: "traefik:3"
    # build: ./traefik/
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  code:
    build: ./code/
    environment:
      - DOCKER_MODS=
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
      - SUDO_PASSWORD=Kennwort1 #optional
      - DEFAULT_WORKSPACE=/workspace #optional
      - PORT=8443
    volumes:
      - "./workspace:/workspace"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code-router.rule=PathPrefix(`/code/`)"
      - "traefik.http.middlewares.code-strip.stripprefix.prefixes=/code"
      - "traefik.http.middlewares.code-strip.stripprefix.forceSlash=false"
      - "traefik.http.routers.code-router.middlewares=code-strip"

  doc:
    build: ./doc/
    volumes:
      - "./doc:/doc"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.doc-router.rule=PathPrefix(`/doc/`)"
      - "traefik.http.middlewares.doc-strip.stripprefix.prefixes=/doc"
      - "traefik.http.middlewares.doc-strip.stripprefix.forceSlash=false"
      - "traefik.http.routers.doc-router.middlewares=doc-strip"
    
